#FROM node:20-alpine3.19 AS build

#WORKDIR /usr/src/rebbl
#COPY package*.json ./
#RUN npm install --production
#RUN npm prune --production
#COPY  . .

#FROM gcr.io/distroless/nodejs:20

#WORKDIR /usr/src/rebbl
#COPY --from=build /usr/src/rebbl .

FROM alpine:3.19.1

RUN apk add --update nodejs npm

RUN addgroup -S node && adduser -S node -G node

USER node

RUN mkdir /home/node/code
RUN mkdir /home/node/code/replays
RUN mkdir /home/node/code/zflstats
RUN mkdir /home/node/code/images
RUN mkdir /home/node/code/images/clanlogos

WORKDIR /home/node/code

COPY --chown=node:node package-lock.json package.json ./

RUN npm install --production

RUN npm prune --production

COPY --chown=node:node . .

CMD ["node","server.js"] 