FROM alpine:latest

RUN apk add --update nodejs npm

RUN addgroup -S node && adduser -S node -G node

USER node

RUN mkdir /home/node/code
RUN mkdir /home/node/code/replays
RUN mkdir /home/node/code/zflstats
RUN mkdir /home/node/code/images
RUN mkdir /home/node/code/images/clanlogos

WORKDIR /home/node/code

COPY --chown=node:node package-lock.json package.json ./

RUN npm install --production

RUN npm prune --production

COPY --chown=node:node . .

CMD ["node","server.js"] 